apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: {{SERVICE_NAME}}
  namespace: {{NAMESPACE}}
  labels:
    zone: default
    app: {{SERVICE_NAME}}
  annotations:
    something: something
spec:
  selector:
    matchLabels:
      app: {{SERVICE_NAME}}
  replicas: {{REPLICAS}}
  {{NODE_AFFINITY}}
  template:
    metadata:
      labels:
        zone: default
        app: {{SERVICE_NAME}}
        prometheus.io/scrape: 'true'
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '8080'
    spec:
      containers:
        - name: {{SERVICE_NAME}}
          image: {{IMAGE}}
          ports:
            - name: mub-cell-port
              containerPort: 8080
          volumeMounts:
            - name: podinfo
              mountPath: /etc/podinfo
            - name: microservice-volume
              mountPath: /app/MSConfig
          env:
            - name: APP
              value: {{SERVICE_NAME}}
            - name: ZONE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['zone']
            - name: K8S_APP
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['app']
            - name: PN
              value: {{PN}}
            - name: TN
              value: {{TN}}
          resources: {{RESOURCES}}    

        {{SIDECAR}}

      volumes:
        - name: podinfo
          downwardAPI:
            items:
              - path: "labels"
                fieldRef:
                  fieldPath: metadata.labels
              - path: "annotations"
                fieldRef:
                  fieldPath: metadata.annotations
        - name: microservice-volume
          persistentVolumeClaim:
            claimName: nfs-pvc-ms
---
apiVersion: v1
kind: Service
metadata:
  name: {{SERVICE_NAME}}
  namespace: {{NAMESPACE}}
  labels:
    app: {{SERVICE_NAME}}
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 8080
    nodePort:
    name: tcp-input-rest
  - port: 51313
    targetPort: 51313
    name: tcp-input-grpc
  selector:
    app: {{SERVICE_NAME}}