apiVersion: v1
kind: ConfigMap
metadata:
  name: microservices-configmap
  namespace: default
data:
  service-mesh: |-
    {"s0": [{"seq_len": 1,
            "services": ["s2", "s3"]
            },
           {"seq_len": 1,
            "services": ["s3"]
            }
           ],
    "s1": [],
    "s2": [{"seq_len": 1,
            "services": ["s4"]}],
    "s3": [],
    "s4": []
    }

  work-model: |-
    {'s0': {'image': 'lucapetrucci/microservice:latest',
           'namespace': 'default',
           'params': {'compute_pi': {'P': 1, 'b': 11, 'c': [101, 101]}},
           'path': '/api/v1',
           'url': 'http://s0.default.svc.cluster.local'},
    's1': {'image': 'lucapetrucci/microservice:latest',
           'namespace': 'default',
           'params': {'compute_pi': {'P': 1, 'b': 11, 'c': [101, 101]}},
           'path': '/api/v1',
           'url': 'http://s1.default.svc.cluster.local'},
    's2': {'image': 'lucapetrucci/microservice:latest',
           'namespace': 'default',
           'params': {'compute_pi': {'P': 1, 'b': 11, 'c': [101, 101]}},
           'path': '/api/v1',
           'url': 'http://s2.default.svc.cluster.local'},
    's3': {'image': 'lucapetrucci/microservice:latest',
           'namespace': 'default',
           'params': {'compute_pi': {'P': 1, 'b': 11, 'c': [101, 101]}},
           'path': '/api/v1',
           'url': 'http://s3.default.svc.cluster.local'},
    's4': {'image': 'lucapetrucci/microservice:latest',
           'namespace': 'default',
           'params': {'compute_pi': {'P': 1, 'b': 11, 'c': [101, 101]}},
           'path': '/api/v1',
           'url': 'http://s4.default.svc.cluster.local'}}