apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-gateway-nginx
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
        app: ms-gateway-nginx
  template:
    metadata:
      labels:
        app: ms-gateway-nginx
    spec:
      containers:
      - name: ms-gateway-nginx
        image: nginx
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /etc/nginx/nginx.conf
          readOnly: true
          name: config-volume
          subPath: nginx.conf
        - mountPath: /var/log/nginx
          name: log
      volumes:
      - name: config-volume
        configMap:
          name: ms-gateway-configmap
      - name: log
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: ms-gw-nginx-svc
  namespace: default
spec:
  type: NodePort
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
      nodePort: 31113
  selector:
    app: ms-gateway-nginx

