apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: s0-dep
  namespace: default
  labels:
    zone: default
    app: s0
  annotations:
    something: something
spec:
  selector:
    matchLabels:
      app: s0-pod
  replicas: 1
  template:
    metadata:
      labels:
        zone: default
        app: s0-pod
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '8081'
    spec:
      containers:
        - name: s0-pod
          image: lucapetrucci/microservice-ssh:latest
          ports:
            - containerPort: 8080
            - containerPort: 22
          volumeMounts:
            - name: podinfo
              mountPath: /etc/podinfo
#            - name: config-volume
#              mountPath: /etc/MSconfig
            - name: job-function-volume
              mountPath: /app/MSConfig
          env:
            - name: APP
              value: s0
            - name: ZONE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['zone']
            - name: K8S_APP
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['app']
#      terminationGracePeriodSeconds: 0
      volumes:
        - name: podinfo
          downwardAPI:
            items:
              - path: "labels"
                fieldRef:
                  fieldPath: metadata.labels
              - path: "annotations"
                fieldRef:
                  fieldPath: metadata.annotations

#        - name: config-volume
#          configMap:
#            name: microservices-configmap
#            items:
#            - key: service-mesh
#              path: servicemesh
#            - key: work-model
#              path: workmodel
        - name: job-function-volume
          persistentVolumeClaim:
            claimName: nfs-pvc-ms
---
apiVersion: v1
kind: Service
metadata:
  name: s0
  namespace: default
  labels:
    app: s0-pod
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 8080
    nodePort:
    name: input
  - port: 9999
    targetPort: 22
    nodePort: 30500
    name: ssh
  selector:
    app: s0-pod