apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: s1-dep
  labels:
    zone: default
    app: s1
  annotations:
    something: something
spec:
  selector:
    matchLabels:
      app: s1-pod
  replicas: 1
  template:
    metadata:
      labels:
        app: s1-pod
    spec:
      containers:
        - name: s1-pod
          image: lucapetrucci/microservice:latest
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: podinfo
              mountPath: /etc/podinfo
            - name: config-volume
              mountPath: /etc/config
          env:
            - name: APP
              value: s1
#      terminationGracePeriodSeconds: 0
      volumes:
        - name: podinfo
          downwardAPI:
            items:
              - path: "labels"
                fieldRef:
                  fieldPath: metadata.labels
              - path: "annotations"
                fieldRef:
                  fieldPath: metadata.annotations
        - name: config-volume
          configMap:
            name: microservices-configmap
            items:
            - key: service-mesh
              path: mesh
            - key: work-model
              path: model
---
apiVersion: v1
kind: Service
metadata:
  name: s1
  labels:
    app: s1-pod
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 8080
    nodePort:
    name: input
  selector:
    app: s1-pod