apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: s1-dep
  labels:
    zone: default
    app: s1
  annotations:
    qualcosa: qualchevalore
spec:
  selector:
    matchLabels:
      app: s1-pod
  replicas: 1
  template:
    metadata:
      labels:
        app: s1-pod
    spec:
      containers:
        - name: s1-pod
          image: lucapetrucci/microservice:latest
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: podinfo
              mountPath: /etc/podinfo
            - mountPath: /app/TestVar.py
              readOnly: true
              name: test-var
              subPath: TestVar.py
          env:
            - name: APP
              value: s1
      volumes:
        - name: podinfo
          downwardAPI:
            items:
              - path: "labels"
                fieldRef:
                  fieldPath: metadata.labels
              - path: "annotations"
                fieldRef:
                  fieldPath: metadata.annotations
        - name: test-var
          configMap:
            name: microservices-configmap